#! /bin/sh


export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_MUSIC_HOME="${XDG_MUSIC_DIR:-$HOME/song}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

envsubst <./mpd.envsubst > ./mpd.conf
